### ISSUE TITLE
1:4 scan rate displays

### ISSUE THREAD

**Issue by NetForces** [adafruit/RGB-matrix-Panel#13]
Hi,

  I got my hand on some super bright outdoor 16x32 display. They are HUB75B, but seems to only use the A and B selects which I believe means they are 1:4 scan rate. Been hacking at it all day without results.

  Any pointers on how I could adapt the library to use those displays ?

Thanks.

**Comment by kartingted** [comment]
I know this is a old post but how did they manage to get it to work? 
really struggling :(

**Comment by datalin** [comment]
@NetForces , did you submit your pull request, will be really helpful if you share how you pulled it off.
