### ISSUE TITLE
Add support for Arduino Due

### ISSUE THREAD

**Issue by plaidpants** [adafruit/RGB-matrix-Panel#16]
Need to fix up the port access, the interrupt, and the assembly but then you would have a board that had enough memory to drive the thing with some graphics.

**Comment by unic8s** [comment]
Would really appreciate this. Sadly there is no response or progress on this topic.

**Comment by sevketk** [comment]
You should update code to support arduino due . or arm processor

**Comment by ladyada** [comment]
hiya the samd21 and samd51 are current supported. we wont add due support any time soon
closing at wontfix.
