### ISSUE TITLE
Spurious .github folder warning

### ISSUE THREAD

**Issue by per1234** [adafruit/RGB-matrix-Panel#26]
The .github folder added in https://github.com/adafruit/RGB-matrix-Panel/commit/14d8b3c78831c4a03fd67a7a5cb6d860bc37e3da (and apparently to all other Adafruit libraries) causes the warning:

```
WARNING: Spurious .github folder in 'RGB matrix Panel' library
```

with Arduino IDE 1.6.6 or greater on every compile, whether the library is included or not. This is annoying and causes confusion for beginners. I would recommend putting the template files in the repository root instead as https://help.github.com/articles/creating-an-issue-template-for-your-repository/ states is allowed.

**Comment by ladyada** [comment]
@per1234 hiya, why not just just Arduino ignore .github the same way it ignores .git?

**Comment by per1234** [comment]
The .github folder has been ignored since arduino-builder 1.3.19 / Arduino IDE 1.6.10:
https://github.com/arduino/arduino-builder/commit/18470b99daca196257205eae9396a1f74f2bd6fe

Actually it was done at your request: https://github.com/arduino/arduino-builder/issues/70#issuecomment-227041842
Thanks!

So at this point the issue only exists for people using outdated versions of the Arduino IDE (1.6.6-1.6.9). Since it's only a warning anyway I'd say the issue can definitely be considered resolved. I just forgot about this issue and so I never closed it.

**Comment by ladyada** [comment]
oh lol, i wasnt watching this repo and just did an issue sweep. well, GOOD WORK PAST US! :D
