### ISSUE TITLE
Support for MKR1000

### ISSUE THREAD

**Issue by LRagji** [adafruit/RGB-matrix-Panel#31]
Hi, I would really love to see support for MKR1000 as that board is powerful in all aspects any support for same anything 

This is not a bug its a feature request?

**Comment by ladyada** [comment]
we support samd21 now

**Comment by bgaebel** [comment]
Are you sure the support of samd21works well?
I have two MKR1000 and when I just add matrix.begin() to my sketch, the boards hangss up and will also disappear from Windows Device Manager (error code 43)

any ideas?

thanks

**Comment by ladyada** [comment]
we havent tested the MKR1000 - that may have a different pinout setup. it works with our samd21 boards for sure!

**Comment by bgaebel** [comment]
Dear ladyada,

it was my fault! I missed the additional parameter *pinlist of the contructor.
Library works as expected for the MKR1000

*thumbs_up

best regards

**Comment by LRagji** [comment]
@bgaebel can you share the pinouts/connection diagram for same?, also the code part of it if possible.

**Comment by bgaebel** [comment]
Sorry, I were to fast with my pleasure.
Just using matrix.begin() works, but until I want to draw any Pixel, the entire board hangs up.

How to figure out, what's going wrong?

On my MKR1000 works an ATSAMW25H18... and there I see the mistake: It's not a SAMD21, it's a SAMW51... 
GOD DAMN IT!

**Comment by LRagji** [comment]
I think this means the defect is still open, as it talks about MKR1000 support?

**Comment by ladyada** [comment]
where we talk about MKR1000 support? we'll remove it
