### ISSUE TITLE
cannot run PanelGFXDemo_16x32 example

### ISSUE THREAD

**Issue by bagustyo92** [adafruit/RGB-matrix-Panel#42]
no function in RGBmatrixPanel.cpp named drawRGBBitmap() that you used on PanelGFXDemo_16x32.cpp file.

- Arduino board:  mega2560
- Arduino IDE version (found in Arduino -> About Arduino menu):  Platform IO based on Arduino IDE 1.8.5
- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): unzip the zip file and import to lib platform IO folder

**Comment by bagustyo92** [comment]
typo in my comment, but surely in the real code is exactly the same that you write, sorry for sure, still not work

![image](https://user-images.githubusercontent.com/28665396/42434802-a22104e2-837e-11e8-8f4b-7183cf321551.png)

**Comment by bagustyo92** [comment]
solved!
the library that i used is not up to date because some reason, thanks

**Comment by marcmerlin** [comment]
Ok, this was the next things I was going to suggest :)   Glad it's solved. 
Can you close the issue please?
