### ISSUE TITLE
Arduino Due

### ISSUE THREAD

**Issue by thepersonamusic** [adafruit/RGB-matrix-Panel#43]
- Arduino board: Arduino Due

- Arduino IDE version (found in Arduino -> About Arduino menu): Web

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): This library appears in the Arduino Web IDE library manager for the Arduino Due, even though it appears to be incompatible.

**Comment by ladyada** [comment]
yep we do not have due code, nor do we have a plan to add it - but if you can add support we will totally accept a pull request :)
