### ISSUE TITLE
Documentation for the library?

### ISSUE THREAD

**Issue by xird** [adafruit/RGB-matrix-Panel#45]
Is there any reference documentation for the RGB matrix Panel library? The tutorial and the examples do shed some light on how to use the library, but they're no substitute for proper documentation.

**Comment by ladyada** [comment]
you can check the GFX library docs
https://learn.adafruit.com/adafruit-gfx-graphics-library
learn guide
https://learn.adafruit.com/32x16-32x32-rgb-led-matrix
and this guide from sparkfun
https://www.sparkfun.com/sparkx/blog/2650
as well as the inline comments :)
