### ISSUE TITLE
Please Mention SmartMatrix::GFX as an alternate library for faster CPUs/higher res panels

### ISSUE THREAD

**Issue by marcmerlin** [adafruit/RGB-matrix-Panel#49]
Please mention this alternate library which supports your ESP32 chips:
https://www.adafruit.com/product/3405

and your 64x64 panel which you state requires a rPi:
https://www.adafruit.com/product/3649

It also solves the issue of channels panels which aren't supported by this lib either.
PR: https://github.com/adafruit/RGB-matrix-Panel/pull/48

GFX compat library: https://github.com/marcmerlin/SmartMatrix_GFX
SmartMatrix: https://github.com/pixelmatix/SmartMatrix
Example  code that becomes compatible with RGB Panels, whether it was written for Adafruit::GFX, FastLED, or LEDMatrix: https://github.com/marcmerlin/FastLED_NeoMatrix_SmartMatrix_LEDMatrix_GFX_Demos/

**Comment by ladyada** [comment]
thanks for the PR - i blieve this is done - reopen or send another PR if not :)
