### ISSUE TITLE
P8 40x20 scan 1/5 

### ISSUE THREAD

**Issue by ainxs** [adafruit/RGB-matrix-Panel#74]
Can i use this library for my panel? Thank you 
![1680668902849179850922668137230](https://user-images.githubusercontent.com/1091831/229981160-9bda26a6-3997-40c5-b2e7-1955debece3a.jpg)

**Comment by marcmerlin** [comment]
there is a near infinite amount of panels, many are incompatible or have different mappings.
The best thing you can do is try it out.
If it doesn't work, try SmartMatrix on teensy or ESP32, or try rpi-rgb-panel on rpi

**Comment by ainxs** [comment]
incompleted
